# Generated by Django 3.1.4 on 2020-12-06 06:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ItinerarioVuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ida', models.DateTimeField()),
                ('fecha_regreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cedula', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('acomodacion', models.CharField(max_length=10, null=True)),
                ('correo', models.CharField(max_length=40)),
                ('pagado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tipo', models.CharField(max_length=10)),
                ('hora_checkin', models.CharField(max_length=10)),
                ('hora_salida', models.CharField(max_length=10)),
                ('hora_retorno', models.CharField(max_length=10)),
                ('lugar_salida', models.CharField(max_length=150)),
                ('imagen', models.ImageField(upload_to='')),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('capacidad', models.IntegerField()),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.pasajero')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.salida'),
        ),
        migrations.CreateModel(
            name='NoIncluye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=900)),
                ('dia', models.IntegerField(null=True)),
                ('siguiente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.itinerario')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Incluye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Importante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=300)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
    ]
