# Generated by Django 3.1.4 on 2021-11-03 20:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6, null=True, unique=True)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('tipo', models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], default='NAC', max_length=3)),
                ('activa', models.BooleanField(default=True)),
                ('codigo_url', models.CharField(max_length=35, null=True, unique=True)),
                ('mostrar_en_menu', models.BooleanField(default=False)),
                ('imagen', models.ImageField(null=True, upload_to='categorias/<built-in function id>')),
                ('icono', models.CharField(default='las la-map-marked', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ItinerarioVuelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ida', models.DateTimeField()),
                ('fecha_regreso', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=30, null=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('acomodacion', models.CharField(max_length=10, null=True)),
                ('correo', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('cedula', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('comprobante', models.CharField(max_length=100, null=True)),
                ('metodo_de_pago', models.CharField(choices=[('PAP', 'Payphone'), ('DEP', 'Depósito o Transferencia')], default='PAP', max_length=3)),
                ('valor', models.IntegerField(default=100)),
                ('estado', models.CharField(choices=[('PEN', 'PENDIENTE'), ('APR', 'APROBADA'), ('PRO', 'PROCESANDO'), ('DBC', 'DE BAJA POR CLIENTE'), ('DBA', 'DE BAJA POR ADMIN')], default='PEN', max_length=3)),
                ('pagado', models.BooleanField(default=False)),
                ('de_baja', models.BooleanField(default=False)),
                ('codigo_cancelacion', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('ubicacion', models.CharField(max_length=60, null=True)),
                ('dificultad', models.CharField(max_length=60, null=True)),
                ('altura', models.CharField(max_length=60, null=True)),
                ('temperatura', models.CharField(max_length=60, null=True)),
                ('trekking', models.CharField(max_length=60, null=True)),
                ('aplica_dificultad', models.BooleanField(default=False)),
                ('aplica_altura', models.BooleanField(default=False)),
                ('aplica_temperatura', models.BooleanField(default=False)),
                ('aplica_trekking', models.BooleanField(default=False)),
                ('hora_checkin', models.CharField(max_length=10)),
                ('hora_salida', models.CharField(max_length=10)),
                ('hora_retorno', models.CharField(max_length=10)),
                ('lugar_salida', models.CharField(max_length=300)),
                ('token', models.CharField(max_length=30, null=True)),
                ('imagen', models.ImageField(upload_to='tours/<built-in function id>')),
                ('tipo', models.CharField(choices=[('NAC', 'Nacional'), ('INT', 'Internacional')], default='NAC', max_length=3)),
                ('precio', models.FloatField()),
                ('duracion', models.IntegerField(default=0)),
                ('abordaje_dia_anterior', models.BooleanField(default=True)),
                ('activo', models.BooleanField(default=False)),
                ('pet_friendly', models.BooleanField(default=False)),
                ('imagen_descripcion', models.ImageField(null=True, upload_to='tours/<built-in function id>/descripcion')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Salida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_salida', models.DateField()),
                ('token', models.CharField(max_length=30, null=True)),
                ('capacidad', models.IntegerField(default=0)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='ReservaPasajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=25, null=True)),
                ('nombres', models.CharField(max_length=100, null=True)),
                ('apellidos', models.CharField(max_length=100, null=True)),
                ('edad', models.IntegerField(null=True)),
                ('cedula', models.CharField(max_length=12, null=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='reserva',
            name='salida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.salida'),
        ),
        migrations.CreateModel(
            name='NoIncluye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Itinerario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.IntegerField(null=True)),
                ('descripcion', models.CharField(max_length=3000, null=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='InteresadoTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Incluye',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('icono', models.CharField(default='las la-check-circle', max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Importante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('cedula', models.CharField(max_length=20, null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
                ('direccion', models.CharField(max_length=150, null=True)),
                ('telefono', models.CharField(max_length=20, null=True)),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.reserva')),
            ],
        ),
    ]
