# Generated by Django 3.1.4 on 2022-01-14 02:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subdominio', models.CharField(max_length=30, null=True)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='tour',
            name='altura',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='aplica_altura',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='aplica_dificultad',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='aplica_temperatura',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='aplica_trekking',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='dificultad',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='imagen_descripcion',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='pet_friendly',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='temperatura',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='trekking',
        ),
        migrations.CreateModel(
            name='EmpresaUsuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main_app.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main_app.empresa'),
        ),
    ]
