# Generated by Django 3.1.4 on 2020-12-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='reservapasajero',
            name='token',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='ubicacion',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
