# Generated by Django 3.1.4 on 2020-12-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201206_1734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importante',
            old_name='nombre',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='incluye',
            old_name='nombre',
            new_name='descripcion',
        ),
        migrations.RemoveField(
            model_name='itinerario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='itinerario',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tour',
            name='descripcion',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
