# Generated by Django 3.1.4 on 2022-01-14 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20220113_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incluye',
            name='icono',
        ),
        migrations.CreateModel(
            name='DetalleTour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('detalle', models.CharField(max_length=100)),
                ('icono', models.CharField(default='las la-check-circle', max_length=100)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.tour')),
            ],
        ),
    ]
