# Generated by Django 3.1.4 on 2020-12-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20201206_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(upload_to='tours'),
        ),
    ]
