# Generated by Django 3.1.4 on 2022-01-14 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220113_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalletour',
            old_name='nombre',
            new_name='descripcion',
        ),
    ]
