# Generated by Django 3.1.4 on 2020-12-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20201206_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='es_internacional',
            field=models.BooleanField(default=False),
        ),
    ]
