# Generated by Django 3.1.4 on 2022-01-14 05:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_auto_20220113_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Empresa',
            new_name='Agencia',
        ),
        migrations.RenameModel(
            old_name='EmpresaUsuario',
            new_name='AgenciaUsuario',
        ),
        migrations.RenameField(
            model_name='agenciausuario',
            old_name='empresa',
            new_name='agencia',
        ),
        migrations.RenameField(
            model_name='tour',
            old_name='empresa',
            new_name='agencia',
        ),
    ]
