# Generated by Django 3.1.4 on 2022-01-14 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20220114_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenciausuario',
            name='logo',
            field=models.ImageField(null=True, upload_to='agencias/<built-in function id>'),
        ),
    ]
