# Generated by Django 3.1.4 on 2020-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_tour_es_internacional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salida',
            name='capacidad',
        ),
        migrations.AddField(
            model_name='tour',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
