# Generated by Django 3.1.4 on 2022-01-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_agenciausuario_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='subdominio',
            field=models.CharField(max_length=31, null=True),
        ),
    ]
