# Generated by Django 2.2.4 on 2021-01-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_auto_20201206_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incluye',
            old_name='descripcion',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='reservapasajero',
            name='pasajero',
        ),
        migrations.AddField(
            model_name='reserva',
            name='de_baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservapasajero',
            name='apellidos',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reservapasajero',
            name='cedula',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='reservapasajero',
            name='nombres',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salida',
            name='token',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='duracion',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Pasajero',
        ),
    ]
