# Generated by Django 3.1.4 on 2022-01-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20220114_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agenciausuario',
            name='logo',
        ),
        migrations.AddField(
            model_name='agencia',
            name='logo',
            field=models.ImageField(null=True, upload_to='agencias/<built-in function id>'),
        ),
    ]
