# Generated by Django 3.1.4 on 2022-01-14 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20220114_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencia',
            name='logo',
            field=models.ImageField(null=True, upload_to='agencias'),
        ),
    ]
